/*
 * generated by Xtext 2.18.0.M3
 */
package de.uni_paderborn.swt.cards.dsl

import org.eclipse.xtext.formatting2.IFormatter2
import de.uni_paderborn.swt.cards.dsl.formatting2.TMDslFormatter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TMDslRuntimeModule extends AbstractTMDslRuntimeModule {
	override Class<? extends IFormatter2> bindIFormatter2() {
		TMDslFormatter
	}
}
