/*
 * generated by Xtext 2.23.0
 */
package de.uni_paderborn.swt.cards.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TMDslUiModule extends AbstractTMDslUiModule {
}
